### ISSUE TITLE
Is the artifact for foundationmodels going to be released?

### ISSUE THREAD

**Issue by sap-ali** [SAP/ai-sdk-java#174]
### Ask the Question

Hi team,

I am trying to use the library in our project but I've noticed that the `foundationmodels` artefact is not released like the other modules.

Is there a plan to release that too?

Thank you!

Kind regards,

**Comment by jjtang1985** [comment]
Actually, we just did a release for `0.2.0`, where the foundation models can be found [here](https://central.sonatype.com/search?q=com.sap.ai.sdk.foundationmodels).
