### ISSUE TITLE
which version is available now?

### ISSUE THREAD

**Issue by Terry-Huang-00** [SAP/ai-sdk-java#50]
hello Experts,

Is this lib available now? I just searched it but I cannot find it.

Best regards,
Terry

**Comment by newtork** [comment]
Either you build and install the library by local checkout, or you use latest `0.1.0-SNAPSHOT` from _SAP Common Artifactory_.
Please note, the latest version uploaded almost 2 months ago. If you're interested in a recent upload, please let me know.

There are more details here:
https://github.com/SAP/ai-sdk-java/wiki/How-To:-Add-dependency-to-project

**Comment by Terry-Huang-00** [comment]
OK, thanks for your explanations, is there any plan to release the first version? Then we can use it in our application.

**Comment by MatKuhr** [comment]
Quick update that an initial alpha version 0.1.0 has been [released to Maven Central](https://central.sonatype.com/search?q=com.sap.ai.sdk&namespace=com.sap.ai.sdk) 🥳

We'll keep releasing such versions leading up to a GA release. Thus I'll close this item.
